// src/utils/seedArtists.js
// One-time seed script — call seedAllArtists() from browser console or a dev button.
// It writes all 20 artists to Firestore collection "artists".

import { db } from "./firebase"
import { doc, setDoc } from "firebase/firestore"

// ── All artist data (moved from data/artists.js for seeding) ──
const ALL_ARTISTS = [
  // ── FEATURED (8 cards always visible) ────────────────────────
  {
    id: "jagjit-singh",
    featured: true,
    imageFile: "jagjit-singh.jpg",
    name: "Jagjit Singh",
    urdu: "جگجیت سنگھ",
    title: "King of Ghazals",
    born: "8 February 1941", died: "10 October 2011",
    origin: "Ganganagar, Rajasthan, India",
    activeYears: "1965 – 2011",
    bio: "Jagjit Singh transformed the ghazal from a niche classical form into a widely accessible genre. Born in Ganganagar, Rajasthan, his voice carried the weight of Urdu poetry to millions who had never read a sher in their lives. With his wife Chitra Singh, he revolutionized the recording of ghazals in the 1980s, stripping away elaborate orchestration to let the poetry breathe.",
    bioShort: "Ghazals that sound like silence, rain and old memories.",
    monthlyListeners: "4.2M", followers: "8.9M", totalSongs: "500+",
    tags: ["Ghazal", "Thumri", "Nazm"],
    color: "#c4a882",
    accentBg: "linear-gradient(160deg, #1a1008 0%, #0e0b06 100%)",
    albums: [
      { title: "Sajda",          year: "1991", tracks: 8  },
      { title: "Unforgettables", year: "1990", tracks: 12 },
      { title: "Marasim",        year: "1981", tracks: 9  },
      { title: "The Latest",     year: "1998", tracks: 10 },
      { title: "Saath Saath",    year: "1982", tracks: 8  },
      { title: "Arth",           year: "1982", tracks: 6  },
    ],
    awards: ["Padma Vibhushan (2003)", "National Film Award", "Filmfare Awards (multiple)"],
    influences: ["Ustad Bade Ghulam Ali Khan", "Mirza Ghalib (poet)", "Faiz Ahmed Faiz (poet)"],
  },
  {
    id: "mehdi-hassan",
    featured: true,
    imageFile: "mehdi-hassan.jpg",
    name: "Mehdi Hassan",
    urdu: "مہدی حسن",
    title: "Shahenshah-e-Ghazal",
    born: "18 July 1927", died: "13 June 2012",
    origin: "Luna, Rajputana, British India",
    activeYears: "1952 – 2010",
    bio: "Mehdi Hassan Khan is widely considered the greatest ghazal singer of all time. His voice — deep, precise, and achingly controlled — gave ordinary Urdu words the weight of scripture. Lata Mangeshkar once said of him: 'He turns ghazal into prayer.'",
    bioShort: "The voice that gave Urdu poetry the weight of scripture.",
    monthlyListeners: "3.1M", followers: "6.2M", totalSongs: "400+",
    tags: ["Ghazal", "Dadra", "Classical"],
    color: "#9a8a7a",
    accentBg: "linear-gradient(160deg, #131110 0%, #0c0b09 100%)",
    albums: [
      { title: "Ranjish Hi Sahi", year: "1974", tracks: 6 },
      { title: "Tum Nahin Aaye",  year: "1972", tracks: 7 },
      { title: "Ghazal",          year: "1977", tracks: 8 },
      { title: "Sarhadein",       year: "1975", tracks: 8 },
      { title: "Live in London",  year: "1979", tracks: 5 },
    ],
    awards: ["Nishan-e-Imtiaz (Pakistan)", "Padma Bhushan (India)", "Pride of Performance Award"],
    influences: ["Ustad Aman Ali Khan", "Ustad Azim Khan"],
  },
  {
    id: "nusrat-fateh-ali-khan",
    featured: true,
    imageFile: "nusrat-fateh-ali-khan.jpg",
    name: "Nusrat Fateh Ali Khan",
    urdu: "نصرت فتح علی خان",
    title: "Shahenshah-e-Qawwali",
    born: "13 October 1948", died: "16 August 1997",
    origin: "Faisalabad, Pakistan",
    activeYears: "1965 – 1997",
    bio: "Nusrat Fateh Ali Khan was a Pakistani musician, primarily a singer of Qawwali — the devotional music of the Sufis. Considered one of the greatest voices ever recorded, his range, stamina, and improvisational genius were unparalleled.",
    bioShort: "Qawwali fire that made the whole world spin.",
    monthlyListeners: "8.7M", followers: "15.4M", totalSongs: "600+",
    tags: ["Qawwali", "Sufi", "Folk"],
    color: "#c47c5a",
    accentBg: "linear-gradient(160deg, #1a0a04 0%, #100604 100%)",
    albums: [
      { title: "Shahen Shah",      year: "1989", tracks: 6  },
      { title: "Mustt Mustt",      year: "1990", tracks: 8  },
      { title: "The Last Prophet", year: "1994", tracks: 10 },
      { title: "Night Song",       year: "1992", tracks: 8  },
      { title: "Chain of Gold",    year: "1997", tracks: 10 },
    ],
    awards: ["UNESCO Music Prize (1995)", "BBC Radio 3 Award for World Music", "Nishan-e-Imtiaz"],
    influences: ["Fateh Ali Khan (father)", "Mubarak Ali Khan (uncle)", "Amir Khusrau (poet)"],
  },
  {
    id: "abida-parveen",
    featured: true,
    imageFile: "abida-parveen.jpg",
    name: "Abida Parveen",
    urdu: "عابدہ پروین",
    title: "Queen of Sufi Music",
    born: "20 February 1954", died: null,
    origin: "Larkana, Sindh, Pakistan",
    activeYears: "1973 – present",
    bio: "Abida Parveen is a Pakistani Sufi singer and one of the most celebrated voices in Islamic and South Asian music. Her performances, often hours long, are described as spiritual experiences that transcend the boundary between music and prayer.",
    bioShort: "Poetry that feels like prayer and stillness that fills a room.",
    monthlyListeners: "2.8M", followers: "4.1M", totalSongs: "300+",
    tags: ["Sufi", "Kafi", "Qawwali"],
    color: "#82b89a",
    accentBg: "linear-gradient(160deg, #071009 0%, #050808 100%)",
    albums: [
      { title: "Raqs-e-Bismil",  year: "2015", tracks: 8  },
      { title: "Ishq",           year: "2007", tracks: 10 },
      { title: "Mast Nazron Se", year: "1998", tracks: 8  },
      { title: "Tu Jhoom",       year: "2022", tracks: 6  },
    ],
    awards: ["Pride of Performance Award (Pakistan)", "Sitara-e-Imtiaz"],
    influences: ["Ustad Salamat Ali Khan", "Bulleh Shah (poet)", "Shah Abdul Latif Bhittai (poet)"],
  },
  {
    id: "ghulam-ali",
    featured: true,
    imageFile: "ghulam-ali.jpg",
    name: "Ghulam Ali",
    urdu: "غلام علی",
    title: "The Velvet Voice",
    born: "1940", died: null,
    origin: "Sialkot, Pakistan",
    activeYears: "1960 – present",
    bio: "Ghulam Ali is a Pakistani ghazal singer known for his velvety, refined voice. A student of Ustad Bade Ghulam Ali Khan, he mastered both the Patiala and Kirana gharanas.",
    bioShort: "Velvet phrasing, old-world refinement.",
    monthlyListeners: "1.9M", followers: "3.2M", totalSongs: "250+",
    tags: ["Ghazal", "Thumri", "Classical"],
    color: "#a89070",
    accentBg: "linear-gradient(160deg, #14100a 0%, #0d0b08 100%)",
    albums: [
      { title: "Chupke Chupke",  year: "1977", tracks: 8  },
      { title: "Aawaz",          year: "1984", tracks: 10 },
      { title: "Meraj-e-Ghazal", year: "1990", tracks: 9  },
    ],
    awards: ["Pride of Performance Award (Pakistan)", "Nishan-e-Imtiaz"],
    influences: ["Ustad Bade Ghulam Ali Khan", "Mir Taqi Mir (poet)"],
  },
  {
    id: "farida-khanum",
    featured: true,
    imageFile: "farida-khanum.jpg",
    name: "Farida Khanum",
    urdu: "فریدہ خانم",
    title: "Mallika-e-Ghazal",
    born: "1935", died: null,
    origin: "Calcutta, British India",
    activeYears: "1950 – present",
    bio: "Farida Khanum is a Pakistani ghazal singer widely known as 'Mallika-e-Ghazal'. Her rendition of 'Aaj Jaane Ki Zid Na Karo' is considered one of the greatest ghazal performances ever recorded.",
    bioShort: "The voice behind the most beloved ghazal ever recorded.",
    monthlyListeners: "1.4M", followers: "2.8M", totalSongs: "200+",
    tags: ["Ghazal", "Thumri"],
    color: "#c4a882",
    accentBg: "linear-gradient(160deg, #1a1008 0%, #0e0b06 100%)",
    albums: [
      { title: "Aaj Jaane Ki Zid Na Karo", year: "1977", tracks: 6 },
      { title: "Mujhe Tum Yaad Aate Ho",   year: "1985", tracks: 8 },
    ],
    awards: ["Pride of Performance Award (Pakistan)", "Tamgha-e-Imtiaz"],
    influences: ["Ustad Ashi Mohammed Khan", "Qateel Shifai (poet)"],
  },
  {
    id: "pankaj-udhas",
    featured: true,
    imageFile: "pankaj-udhas.jpg",
    name: "Pankaj Udhas",
    urdu: "پنکج ادھاس",
    title: "Ghazal for the Masses",
    born: "17 May 1951", died: "26 February 2024",
    origin: "Jetpur, Gujarat, India",
    activeYears: "1980 – 2023",
    bio: "Pankaj Udhas was an Indian ghazal singer who brought the ghazal to mainstream Bollywood audiences. His album Aahat (1980) was a landmark, and 'Chitthi Aayi Hai' became an anthem for the Indian diaspora.",
    bioShort: "The ghazal that reached every household in India.",
    monthlyListeners: "1.2M", followers: "2.1M", totalSongs: "180+",
    tags: ["Ghazal", "Bollywood"],
    color: "#b8a080",
    accentBg: "linear-gradient(160deg, #161208 0%, #0e0c07 100%)",
    albums: [
      { title: "Aahat",     year: "1980", tracks: 8  },
      { title: "Nayaab",    year: "1985", tracks: 10 },
      { title: "Aafreen",   year: "1994", tracks: 9  },
      { title: "Tarrannum", year: "1993", tracks: 8  },
    ],
    awards: ["Padma Shri (2006)", "Filmfare Awards (multiple)"],
    influences: ["Mehdi Hassan", "Jagjit Singh"],
  },
  {
    id: "talat-aziz",
    featured: true,
    imageFile: "talat-aziz.jpg",
    name: "Talat Aziz",
    urdu: "طلعت عزیز",
    title: "The Sophisticated Voice",
    born: "1956", died: null,
    origin: "Hyderabad, India",
    activeYears: "1975 – present",
    bio: "Talat Aziz is an Indian ghazal singer known for his sophisticated, understated style. He has performed at Carnegie Hall and the Royal Albert Hall and is credited with keeping the classical ghazal tradition alive.",
    bioShort: "Understated elegance. Each word placed like a brushstroke.",
    monthlyListeners: "0.8M", followers: "1.4M", totalSongs: "150+",
    tags: ["Ghazal", "Classical"],
    color: "#908070",
    accentBg: "linear-gradient(160deg, #111009 0%, #0c0b08 100%)",
    albums: [
      { title: "Rang",    year: "1991", tracks: 8 },
      { title: "Tasveer", year: "1988", tracks: 9 },
    ],
    awards: ["Sangeet Natak Akademi Award"],
    influences: ["Ustad Ghulam Mustafa Khan", "Faiz Ahmed Faiz (poet)"],
  },

  // ── NON-FEATURED (appear only in search) ─────────────────────
  {
    id: "lata-mangeshkar",
    featured: false,
    imageFile: null,
    name: "Lata Mangeshkar",
    urdu: "لتا منگیشکر",
    title: "Nightingale of India",
    born: "28 September 1929", died: "6 February 2022",
    origin: "Indore, Central Provinces, British India",
    activeYears: "1942 – 2022",
    bio: "Lata Mangeshkar is regarded as one of the greatest and most influential singers in the history of Indian music. She recorded songs in over thirty-six Indian languages over a career spanning seven decades.",
    bioShort: "The voice that defined Indian cinema for seven decades.",
    monthlyListeners: "12.1M", followers: "22.4M", totalSongs: "1000+",
    tags: ["Film", "Classical", "Semi-Classical"],
    color: "#c4a8b8",
    accentBg: "linear-gradient(160deg, #180d12 0%, #0e080c 100%)",
    albums: [
      { title: "Woh Kaun Thi", year: "1964", tracks: 8 },
      { title: "Ajanabee",     year: "1974", tracks: 10 },
    ],
    awards: ["Bharat Ratna (2001)", "Padma Bhushan", "Padma Vibhushan", "Dadasaheb Phalke Award"],
    influences: ["Noor Jehan", "Ustad Amanat Ali Khan"],
  },
  {
    id: "bhupinder-singh",
    featured: false,
    imageFile: null,
    name: "Bhupinder Singh",
    urdu: "بھوپندر سنگھ",
    title: "Voice of the Road",
    born: "6 February 1940", died: "18 July 2022",
    origin: "Amritsar, Punjab, India",
    activeYears: "1964 – 2022",
    bio: "Bhupinder Singh was an Indian playback singer and guitarist known for his soulful, husky voice. His Gulzar collaborations — 'Dil Dhoondta Hai', 'Do Diwane Shehar Mein' — are considered classics of introspective Bollywood music.",
    bioShort: "Husky voice, open roads, Gulzar poetry.",
    monthlyListeners: "0.9M", followers: "1.6M", totalSongs: "200+",
    tags: ["Film", "Ghazal", "Folk"],
    color: "#8a9a70",
    accentBg: "linear-gradient(160deg, #0c1008 0%, #080c06 100%)",
    albums: [
      { title: "Mausam",            year: "1975", tracks: 8 },
      { title: "Do Diwane Shehar Mein", year: "1977", tracks: 6 },
    ],
    awards: ["Filmfare Award for Best Male Playback Singer"],
    influences: ["Hemant Kumar", "Manna Dey"],
  },
  {
    id: "iqbal-bano",
    featured: false,
    imageFile: null,
    name: "Iqbal Bano",
    urdu: "اقبال بانو",
    title: "Voice of Resistance",
    born: "1935", died: "21 April 2009",
    origin: "Delhi, British India",
    activeYears: "1952 – 2009",
    bio: "Iqbal Bano was a Pakistani classical singer best known for her renditions of Faiz Ahmed Faiz's revolutionary poetry. Her 1985 concert where she sang 'Hum Dekhenge' in a sari — defying Zia-ul-Haq's dress code — is legendary in Pakistani cultural history.",
    bioShort: "She sang revolution in a whisper.",
    monthlyListeners: "0.7M", followers: "1.1M", totalSongs: "150+",
    tags: ["Ghazal", "Classical", "Thumri"],
    color: "#a070a8",
    accentBg: "linear-gradient(160deg, #120a14 0%, #0c080e 100%)",
    albums: [
      { title: "Hum Dekhenge", year: "1985", tracks: 6 },
      { title: "Dast-e-Saba",  year: "1979", tracks: 8 },
    ],
    awards: ["Pride of Performance Award (Pakistan)"],
    influences: ["Ustad Barkat Ali Khan", "Faiz Ahmed Faiz (poet)"],
  },
  {
    id: "rahat-fateh-ali-khan",
    featured: false,
    imageFile: null,
    name: "Rahat Fateh Ali Khan",
    urdu: "راحت فتح علی خان",
    title: "Heir to the Throne",
    born: "9 December 1974", died: null,
    origin: "Faisalabad, Pakistan",
    activeYears: "1995 – present",
    bio: "Rahat Fateh Ali Khan is a Pakistani singer known for Sufi and qawwali music. Nephew of Nusrat Fateh Ali Khan, he has successfully bridged the gap between classical qawwali and contemporary Bollywood music.",
    bioShort: "Carrying Nusrat's flame into the modern age.",
    monthlyListeners: "5.8M", followers: "9.2M", totalSongs: "350+",
    tags: ["Qawwali", "Sufi", "Bollywood"],
    color: "#c4905a",
    accentBg: "linear-gradient(160deg, #180e04 0%, #100906 100%)",
    albums: [
      { title: "Jiya Dhadak Dhadak", year: "2006", tracks: 8  },
      { title: "O Re Piya",          year: "2007", tracks: 6  },
      { title: "Tere Mast Mast Do Nain", year: "2010", tracks: 10 },
    ],
    awards: ["Tamgha-e-Imtiaz (Pakistan)", "Filmfare Award"],
    influences: ["Nusrat Fateh Ali Khan", "Fateh Ali Khan"],
  },
  {
    id: "begum-akhtar",
    featured: false,
    imageFile: null,
    name: "Begum Akhtar",
    urdu: "بیگم اختر",
    title: "Mallika-e-Thumri",
    born: "7 October 1914", died: "30 October 1974",
    origin: "Faizabad, United Provinces, British India",
    activeYears: "1930 – 1974",
    bio: "Begum Akhtar was an Indian singer and actress known for her gayaki in thumri, dadra, ghazal and chaiti. She is considered the definitive voice of Urdu ghazal and one of the greatest musical figures of twentieth-century India.",
    bioShort: "The original. Every ghazal singer walks in her shadow.",
    monthlyListeners: "0.5M", followers: "0.9M", totalSongs: "300+",
    tags: ["Ghazal", "Thumri", "Dadra", "Classical"],
    color: "#c4a060",
    accentBg: "linear-gradient(160deg, #1a1204 0%, #0e0c04 100%)",
    albums: [
      { title: "Ae Mohabbat",      year: "1950", tracks: 6 },
      { title: "Aye Dil-e-Nadan", year: "1965", tracks: 8 },
    ],
    awards: ["Padma Shri (1968)", "Padma Bhushan (1975, posthumous)", "Sangeet Natak Akademi Award"],
    influences: ["Ustad Ata Mohammad Khan", "Ustad Abdul Wahid Khan"],
  },
  {
    id: "hariharan",
    featured: false,
    imageFile: null,
    name: "Hariharan",
    urdu: "ہری ہرن",
    title: "The Crossover Voice",
    born: "3 April 1955", died: null,
    origin: "Mumbai, Maharashtra, India",
    activeYears: "1977 – present",
    bio: "Hariharan is an Indian playback singer known for his versatility across ghazal, classical, and film music. His ghazal albums and his fusion project Colonial Cousins brought sophisticated music to a new generation of listeners.",
    bioShort: "Where Carnatic tradition meets Urdu poetry.",
    monthlyListeners: "1.5M", followers: "2.7M", totalSongs: "200+",
    tags: ["Ghazal", "Carnatic", "Bollywood", "Fusion"],
    color: "#7090c4",
    accentBg: "linear-gradient(160deg, #080e18 0%, #060a10 100%)",
    albums: [
      { title: "Hariharan",         year: "1990", tracks: 10 },
      { title: "Kaash",             year: "1997", tracks: 8  },
      { title: "Colonial Cousins",  year: "1996", tracks: 10 },
    ],
    awards: ["National Film Award for Best Male Playback Singer", "Filmfare Awards (multiple)"],
    influences: ["Mehdi Hassan", "Jagjit Singh", "M. S. Subbulakshmi"],
  },
  {
    id: "chitra-singh",
    featured: false,
    imageFile: null,
    name: "Chitra Singh",
    urdu: "چترا سنگھ",
    title: "The Silent Half",
    born: "16 April 1938", died: null,
    origin: "Calcutta, West Bengal, India",
    activeYears: "1967 – 1990",
    bio: "Chitra Singh is an Indian ghazal singer and the wife of Jagjit Singh. Together they recorded landmark albums that transformed the ghazal's commercial and artistic landscape in the 1970s and 80s. After their son's death in 1990, she retired from music.",
    bioShort: "She sang half the story — then chose silence.",
    monthlyListeners: "0.4M", followers: "0.7M", totalSongs: "100+",
    tags: ["Ghazal", "Duet"],
    color: "#c4a882",
    accentBg: "linear-gradient(160deg, #1a1008 0%, #0e0b06 100%)",
    albums: [
      { title: "Unforgettables", year: "1976", tracks: 12 },
      { title: "A Milestone",    year: "1979", tracks: 10 },
    ],
    awards: ["Various collaborative awards with Jagjit Singh"],
    influences: ["Jagjit Singh", "Ustad Bade Ghulam Ali Khan"],
  },
  {
    id: "gulzar",
    featured: false,
    imageFile: null,
    name: "Gulzar",
    urdu: "گلزار",
    title: "Poet of the Everyday",
    born: "18 August 1934", died: null,
    origin: "Dina, Punjab, British India",
    activeYears: "1956 – present",
    bio: "Gulzar is an Indian poet, lyricist, and film director. Though primarily a songwriter, his ghazals and nazms have been sung by every major artist of the 20th century. His words — finding the extraordinary in ordinary things — define a generation of Urdu-Hindi poetry.",
    bioShort: "He wrote the words everyone else sang.",
    monthlyListeners: "3.2M", followers: "6.8M", totalSongs: "1000+",
    tags: ["Nazm", "Ghazal", "Poet"],
    color: "#70a890",
    accentBg: "linear-gradient(160deg, #081210 0%, #060e0a 100%)",
    albums: [
      { title: "Dil Padosi Hai",  year: "1987", tracks: 8 },
      { title: "Sunset Point",    year: "2002", tracks: 10 },
    ],
    awards: ["Padma Bhushan (2004)", "Oscar Award for Jai Ho (2009)", "Sahitya Akademi Award"],
    influences: ["Mirza Ghalib", "Faiz Ahmed Faiz", "Shailendra"],
  },
  {
    id: "ustad-amanat-ali-khan",
    featured: false,
    imageFile: null,
    name: "Ustad Amanat Ali Khan",
    urdu: "استاد امانت علی خان",
    title: "Voice of the Patiala Gharana",
    born: "1922", died: "1974",
    origin: "Patiala, Punjab, British India",
    activeYears: "1945 – 1974",
    bio: "Ustad Amanat Ali Khan was a Pakistani classical vocalist of the Patiala gharana. Known for his thumri and ghazal, his voice combined technical mastery with profound emotional depth. He remains a touchstone for Pakistani classical music.",
    bioShort: "Patiala gharana at its most refined.",
    monthlyListeners: "0.3M", followers: "0.5M", totalSongs: "150+",
    tags: ["Classical", "Thumri", "Ghazal"],
    color: "#c4a060",
    accentBg: "linear-gradient(160deg, #1a1204 0%, #0e0c04 100%)",
    albums: [
      { title: "Patiala Gharana", year: "1965", tracks: 8 },
    ],
    awards: ["Pride of Performance Award (Pakistan)"],
    influences: ["Ustad Asha Ali Khan", "Ustad Fateh Ali Khan"],
  },
  {
    id: "shiv-kumar-batalvi",
    featured: false,
    imageFile: null,
    name: "Shiv Kumar Batalvi",
    urdu: "شیو کمار بٹالوی",
    title: "The Nightingale of Punjab",
    born: "23 July 1936", died: "6 May 1973",
    origin: "Bara Pind Lohtian, Punjab, British India",
    activeYears: "1960 – 1973",
    bio: "Shiv Kumar Batalvi was a Punjabi poet whose deeply personal, anguished poetry about love and loss made him one of the most beloved poets of the Punjab. Though not a singer himself, his poetry is sung by virtually every major Punjabi and ghazal artist.",
    bioShort: "He bled onto paper and called it poetry.",
    monthlyListeners: "1.8M", followers: "3.1M", totalSongs: "50+",
    tags: ["Punjabi", "Poet", "Sufi"],
    color: "#c07050",
    accentBg: "linear-gradient(160deg, #180a04 0%, #100804 100%)",
    albums: [
      { title: "Loona",           year: "1965", tracks: 6 },
      { title: "Birha Da Sultan", year: "1970", tracks: 8 },
    ],
    awards: ["Sahitya Akademi Award (1967, youngest recipient ever)"],
    influences: ["Bulleh Shah", "Waris Shah"],
  },
  {
    id: "ustad-rashid-khan",
    featured: false,
    imageFile: null,
    name: "Ustad Rashid Khan",
    urdu: "استاد راشد خان",
    title: "Rampur Gharana's Last Giant",
    born: "1 July 1966", died: "9 January 2024",
    origin: "Badaun, Uttar Pradesh, India",
    activeYears: "1978 – 2024",
    bio: "Ustad Rashid Khan was an Indian classical vocalist of the Rampur-Sahaswan gharana. Known for his powerful, flexible voice and deep knowledge of classical ragas, he was one of the last truly great khayal singers.",
    bioShort: "Khayal in the old tradition, sung for the modern world.",
    monthlyListeners: "0.6M", followers: "1.1M", totalSongs: "200+",
    tags: ["Classical", "Khayal", "Thumri"],
    color: "#8070c4",
    accentBg: "linear-gradient(160deg, #0c0818 0%, #080610 100%)",
    albums: [
      { title: "Bandish",      year: "2000", tracks: 8 },
      { title: "Raga Yaman",   year: "1995", tracks: 6 },
    ],
    awards: ["Padma Bhushan (2022)", "Sangeet Natak Akademi Award", "Padma Shri (2006)"],
    influences: ["Ustad Nissar Hussain Khan", "Bade Ghulam Ali Khan"],
  },
  {
    id: "malika-pukhraj",
    featured: false,
    imageFile: null,
    name: "Malika Pukhraj",
    urdu: "ملکہ پکھراج",
    title: "The Eternal Voice of Kashmir",
    born: "1912", died: "14 February 2004",
    origin: "Wazirabad, Punjab, British India",
    activeYears: "1926 – 1985",
    bio: "Malika Pukhraj was a Pakistani classical and ghazal singer, best known for her timeless rendition of 'Abhi To Main Jawan Hoon'. Her voice combined the grandeur of Kashmiri classical music with Urdu poetry's emotional precision.",
    bioShort: "Abhi to main jawan hoon — forever.",
    monthlyListeners: "0.4M", followers: "0.6M", totalSongs: "100+",
    tags: ["Ghazal", "Classical", "Thumri"],
    color: "#b49060",
    accentBg: "linear-gradient(160deg, #181008 0%, #0e0c06 100%)",
    albums: [
      { title: "Abhi To Main Jawan Hoon", year: "1958", tracks: 6 },
    ],
    awards: ["Pride of Performance Award (Pakistan)", "Tamgha-e-Imtiaz"],
    influences: ["Ustad Barkat Ali Khan"],
  },
]

/**
 * Seeds all 20 artists into Firestore.
 * Call from browser console:  import('/src/utils/seedArtists.js').then(m => m.seedAllArtists())
 */
export async function seedAllArtists() {
  console.log("🎵 Seeding artists to Firestore...")
  let count = 0

  for (const artist of ALL_ARTISTS) {
    const { id, ...data } = artist
    try {
      await setDoc(doc(db, "artists", id), data)
      count++
      console.log(`  ✓ ${artist.name}`)
    } catch (err) {
      console.error(`  ✗ ${artist.name}:`, err)
    }
  }

  console.log(`\n🎵 Done! Seeded ${count}/${ALL_ARTISTS.length} artists.`)
  return count
}
